// The Storyboard Library — curated, browsable product-storyboard examples:
// each entry is a complete worked example (the 9-panel sheet, the full
// Seedance prompt, and the rendered video result) that a creator can study
// or load straight into Make to generate the same kind of spot for their
// own product. Assets are hosted in Supabase Storage under assets/library/
// (uploaded by scripts, not tied to any user account).

import type { Asset } from "./types";

export interface StoryboardExample {
  id: string;
  /** Commercial name shown on the card. */
  title: string;
  /** The hero product in one line. */
  product: string;
  /** The full Seedance prompt — scene by scene, sized to durationSec. */
  prompt: string;
  /** The commercial's length in seconds (5 / 10 / 15). */
  durationSec: number;
  /** Aspect ratio the video result was rendered at. */
  aspectRatio: string;
  /** The one-image 9-panel storyboard sheet. */
  sheetUrl: string;
  /** The rendered Seedance result (empty while a render is pending). */
  videoUrl: string;
}

/**
 * A storyboard's video length, read back from the saved asset: the explicit
 * "Video length" part when present, else the "<N>-second" opening the writer
 * always puts in the prompt. Returns null when neither matches 5/10/15.
 */
export function storyboardDurationSec(a: Pick<Asset, "parts" | "promptFragment">): number | null {
  const part = a.parts?.find((p) => p.label.startsWith("Video length"));
  const fromPart = part ? parseInt(part.url, 10) : NaN;
  if ([5, 10, 15].includes(fromPart)) return fromPart;
  const m = a.promptFragment?.match(/(\d{1,2})[-\s]second/i);
  const fromPrompt = m ? parseInt(m[1], 10) : NaN;
  return [5, 10, 15].includes(fromPrompt) ? fromPrompt : null;
}

// Entries are generated by scripts/ (Claude prompts → Seedream sheets →
// Seedance videos) and checked in here as data. Brand-free by design.
export const STORYBOARD_LIBRARY: StoryboardExample[] = [
  {
    "id": "strawberry-kefir",
    "title": "Strawberry Kefir Swirl",
    "product": "Pink strawberry kefir bottle",
    "prompt": "A premium 15-second commercial for a pink strawberry kefir drink. Ultra realistic product advertising, macro cinematography, slow-motion liquid and particle simulation, hard key light with soft rim light, photorealistic detail. Scene 1 (0-3s): The sleek pink strawberry kefir bottle with soft pink label, white cap and printed fresh strawberries rests on a glossy pink surface as condensation beads and slides down its curve; extreme macro, slow dolly-in, soft diffused pink key light. Scene 2 (3-6s): A creamy white kefir crown splash erupts in midair beside the same bottle, droplets suspended in slow motion; macro orbit, hard top key light, warm rim light. Scene 3 (6-9s): Ripe strawberries burst upward then tumble and fall, juice ribbons trailing, physics of scattering pulp and spray; whip-pan following the fruit, bright studio backlight. Scene 4 (9-12s): Pink strawberry liquid and white kefir swirl and marble together in a hypnotic vortex; extreme macro, slow rotation, glowing pink fill light. Scene 5 (12-15s): The identical bottle rises triumphantly from the swirl for a full hero reveal, splashes settling; slow crane-up, speed ramp, crisp key and rim light. Audio: uplifting modern pop with playful percussion, synced splash and bright fruit-pop foley. The product is consistent throughout: sleek pink strawberry kefir bottle, soft pink label, white cap, printed strawberries. Fresh, creamy, blush-pink dreamy grade.",
    "durationSec": 15,
    "aspectRatio": "9:16",
    "sheetUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-strawberry-kefir.png",
    "videoUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-strawberry-kefir.mp4"
  },
  {
    "id": "choco-caramel-bar",
    "title": "Golden Snap",
    "product": "Chocolate caramel nut bar",
    "prompt": "A premium 10-second commercial for a chocolate caramel nut bar. Ultra realistic product advertising with macro cinematography, slow-motion liquid and particle simulation, hard studio lighting, and photorealistic detail, set in a deep amber-to-black void. Scene 1 (0-3s): the milk-chocolate caramel nut bar in its glossy deep-red wrapper with bold cream band whips toward camera spinning fast on its axis, a bright specular streak raking across the wrapper, camera locked with a snap zoom, hard amber key light and a cool rim light. Scene 2 (0-3s), smash cut (3-6s): extreme macro of the same glossy deep-red wrapper with cream band tearing open, foil crinkling and peeling, camera orbiting tight, warm hard key light glinting on the tear edge. Scene 3 (6-10s): the bar snaps in two in mid-air, golden caramel stretching in ropey slow-motion strands as roasted peanuts scatter and tumble, whip-pan resolving to a glossy hero shot with a crisp cream rim light, deep amber key light. Audio: punchy cinematic bass-hit electronic track, rising energy, with a crisp wrapper-tear crunch and a satisfying chocolate snap synced to the break. The product is consistent throughout: a milk-chocolate bar filled with golden caramel and roasted peanuts in a glossy deep-red wrapper with a bold cream band. Rich, appetizing, high-contrast amber-and-black grade.",
    "durationSec": 10,
    "aspectRatio": "9:16",
    "sheetUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-choco-caramel-bar.png",
    "videoUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-choco-caramel-bar.mp4"
  },
  {
    "id": "brownie-cone",
    "title": "Cobalt Choco Brownie Reveal",
    "product": "Choco brownie ice-cream cone",
    "prompt": "A premium 10-second commercial for a choco brownie ice-cream cone. Ultra realistic product advertising with macro cinematography, slow-motion liquid and particle simulation, hard studio key light, crisp rim light, and photorealistic detail on an electric cobalt-blue studio background, no people, no hands. Scene 1 (0-2s): extreme macro glides across the cocoa wafer texture of a chocolate wafer cone in a gold-and-brown wrapper, dimples and grain catching a hard white key light against cobalt blue. Scene 2 (2-4s): orbit shot as chocolate ice cream swirls and fills the cone, glossy ripples settling under a blue rim light, the same wrapper glinting. Scene 3 (4-6s): backlit slow-motion of brownie chunks and almond pieces tumbling onto the topping, crumbs scattering and bouncing, whip-pan following each piece. Scene 4 (6-8s): macro of molten chocolate drizzle pouring and folding into glossy ribbons over the brownie and almonds, thick liquid coating and beading. Scene 5 (8-10s): speed-ramp hero reveal as the complete cone rises into frame, rotating slowly, rim light blazing on cobalt blue. Audio: uplifting cinematic electronic swell with punchy percussion, synced crunch of falling almonds and a wet chocolate pour. The product is consistent throughout: a chocolate wafer cone in a gold-and-brown wrapper, filled with chocolate ice cream, topped with brownie chunks and almond pieces under a glossy chocolate drizzle. Rich, decadent mood with a saturated cobalt-and-cocoa grade.",
    "durationSec": 10,
    "aspectRatio": "9:16",
    "sheetUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-brownie-cone.png",
    "videoUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-brownie-cone.mp4"
  },
  {
    "id": "citrus-energy-can",
    "title": "Wake Up Wired",
    "product": "Ice-blue citrus energy drink can",
    "prompt": "A premium 15-second commercial for an ice-blue citrus energy drink can. Ultra realistic product advertising with macro cinematography, slow-motion liquid and particle simulation, naturalistic studio lighting and pore-level photorealistic detail. Scene 1 (0-3s): The can sweats on a white studio table, condensation beads swelling and sliding down the frosted aluminium in slow motion, macro push-in, soft cool daylight key with silver rim light. The product: a slim 0.33L aluminium energy drink can in ice-blue and silver with a frosted matte finish and beads of condensation. Scene 2 (3-6s): A glossy sculpted cartoon punk head with a magenta-and-blue mohawk and chain piercings wakes beside the can, eyes snapping open, slow orbit around both, hard key light with blue rim. The same can stays hero-lit. Scene 3 (6-9s): The head spots the can and its oversized jaw drops in exaggerated craving, drool glinting, whip-pan to the can as droplets scatter. Scene 4 (9-12s): The punk head lunges and chomps air, chain piercings swinging, speed ramp; the identical ice-blue can holds steady, mist curling. Scene 5 (12-15s): Full hero reveal, the can upright in a swirling halo of icy mist, slow crane up, triumphant rim light. Audio: pounding electro-punk with a bass drop synced to the jaw drop and a crisp can-crack fizz. The product is consistent throughout: a slim 0.33L aluminium energy drink can in ice-blue and silver with a frosted matte finish and beads of condensation. Cool, crisp, electric-blue color grade.",
    "durationSec": 15,
    "aspectRatio": "9:16",
    "sheetUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-citrus-energy-can.png",
    "videoUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-citrus-energy-can.mp4"
  }
];
