// The Storyboard Library — curated, browsable product-storyboard examples:
// each entry is a complete worked example (the 9-panel sheet, the full
// Seedance prompt, and the rendered video result) that a creator can study
// or load straight into Make to generate the same kind of spot for their
// own product. Assets are hosted in Supabase Storage under assets/library/
// (uploaded by scripts, not tied to any user account).

import type { Asset } from "./types";

export interface StoryboardExample {
  id: string;
  /** Commercial name shown on the card. */
  title: string;
  /** The hero product in one line. */
  product: string;
  /** The full Seedance prompt — scene by scene, sized to durationSec. */
  prompt: string;
  /** The commercial's length in seconds (5 / 10 / 15). */
  durationSec: number;
  /** Aspect ratio the video result was rendered at. */
  aspectRatio: string;
  /** The one-image 9-panel storyboard sheet. */
  sheetUrl: string;
  /** The rendered Seedance result (empty while a render is pending). */
  videoUrl: string;
}

/**
 * A storyboard's video length, read back from the saved asset: the explicit
 * "Video length" part when present, else the "<N>-second" opening the writer
 * always puts in the prompt. Returns null when neither matches 5/10/15.
 */
export function storyboardDurationSec(a: Pick<Asset, "parts" | "promptFragment">): number | null {
  const part = a.parts?.find((p) => p.label.startsWith("Video length"));
  const fromPart = part ? parseInt(part.url, 10) : NaN;
  if ([5, 10, 15].includes(fromPart)) return fromPart;
  const m = a.promptFragment?.match(/(\d{1,2})[-\s]second/i);
  const fromPrompt = m ? parseInt(m[1], 10) : NaN;
  return [5, 10, 15].includes(fromPrompt) ? fromPrompt : null;
}

// Entries are generated by scripts/ (Claude prompts → Seedream sheets →
// Seedance videos) and checked in here as data. Brand-free by design.
export const STORYBOARD_LIBRARY: StoryboardExample[] = [
  {
    "id": "strawberry-kefir",
    "title": "Strawberry Kefir Swirl",
    "product": "Pink strawberry kefir bottle",
    "prompt": "Create a premium 15 second commercial for a sleek plastic bottle of strawberry kefir with a soft pink label, white cap, and fresh strawberries printed on it. Ultra realistic product advertising, high end beverage commercial, macro cinematography, slow motion liquid simulation, studio lighting, 4K quality, photorealistic details.\n\nScene 1 (0 to 3s): Extreme macro of creamy white kefir forming a perfect slow-motion crown splash, thick droplets suspended and rippling with glossy surface tension. Camera pushes in low across the milky surface as bright soft backlight creates glowing translucent highlights on the pink-tinted rim.\n\nScene 2 (3 to 6s): Ripe strawberries burst upward through the creamy liquid in slow motion, seeds and juice scattering, red flesh catching light. The camera whip-pans upward following the fruit as it rises, soft studio light rimming each berry with a warm pink glow.\n\nScene 3 (6 to 9s): Strawberries fall back down, plunging into the white kefir and sending secondary splashes outward. Pink strawberry juice and white kefir begin swirling together in elegant marbled ribbons, camera orbiting slowly around the vortex under bright directional light.\n\nScene 4 (9 to 12s): The pink and white swirl accelerates into a spinning column; the sleek plastic bottle of strawberry kefir with soft pink label, white cap and printed strawberries rises from the swirling liquid, condensation beading on its surface. Slow cinematic push-in with rim light tracing its silhouette.\n\nScene 5 (12 to 15s): Final packshot — the identical strawberry kefir bottle perfectly centered on a soft pink studio background, symmetrical composition, premium hero lighting with subtle reflections, gentle floating strawberries in the background. Subtle camera hold.\n\nStyle: Glossy high-end beverage advertising, realistic fluid physics, creamy and juicy textures, soft pink and milky white palette with ripe red accents, clean premium studio environment, hyper detailed product rendering, smooth speed-ramped transitions, elegant motion; no people, no text overlays, no watermark, no distortion, no extra products.\n\nAudio: Crisp liquid splashes, soft berry bursts and beading condensation foley synced to each action, over an uplifting airy modern track building to a bright swell, ending in clean silence.",
    "durationSec": 15,
    "aspectRatio": "9:16",
    "sheetUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-strawberry-kefir-v2.png",
    "videoUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-strawberry-kefir-v2.mp4"
  },
  {
    "id": "choco-caramel-bar",
    "title": "Snap Into Caramel",
    "product": "Chocolate caramel nut bar",
    "prompt": "Create a premium 10 second commercial for a chocolate caramel nut bar — a milk-chocolate bar filled with golden caramel and roasted peanuts, in a glossy deep-red wrapper with a bold cream band. Ultra realistic product advertising, high end confectionery commercial, macro cinematography, slow motion caramel simulation, studio lighting, 4K quality, photorealistic details.\n\nScene 1 (0 to 3s): In a deep amber-to-black void, the glossy deep-red wrapped bar with its bold cream band whips toward camera spinning fast on its axis, a bright specular streak racing across the glossy foil. Camera holds low as the bar rockets closer with motion blur, then a speed ramp slams it to a stop. Hard key light glints off the wrapper's crinkled edges against warm amber haze.\n\nScene 2 (3 to 5s): Hard smash cut to extreme macro of the same deep-red wrapper with cream band; the foil tears open with a crisp rip, edges peeling back in slow motion to reveal glossy milk chocolate beneath. Camera pushes in tight, rim light tracing the torn foil's metallic sheen against the black void.\n\nScene 3 (5 to 7s): The milk-chocolate bar snaps in two in mid-air, thick golden caramel stretching into a glistening bridge between the halves while roasted peanuts scatter and tumble in slow motion. Extreme macro orbit captures the caramel's viscous pull and the fractured chocolate texture. Hard backlight makes the caramel glow translucent.\n\nScene 4 (7 to 10s): Final packshot — the intact deep-red wrapped bar with bold cream band, perfectly centered and symmetrical, floating in the amber-to-black void beside its broken half oozing caramel. Slow cinematic push-in with a subtle hold, sharp rim light and glossy premium reflections.\n\nStyle: high end confectionery advertising, realistic caramel and chocolate physics, glossy foil, viscous stretch, crunchy peanut texture, deep-red, cream and warm amber palette, black studio void, hyper detailed product rendering, smooth speed-ramp transitions, elegant motion; no people, no text overlays, no watermark, no distortion, no extra products.\n\nAudio: crisp foil-tear rip, a deep whoosh on the spin, a satisfying snap and soft caramel squelch with pattering peanuts, punchy energetic beat resolving into clean premium sound design ending in silence.",
    "durationSec": 10,
    "aspectRatio": "9:16",
    "sheetUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-choco-caramel-bar-v2.png",
    "videoUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-choco-caramel-bar-v2.mp4"
  },
  {
    "id": "brownie-cone",
    "title": "Choco Brownie Cone Reveal",
    "product": "Choco brownie ice-cream cone",
    "prompt": "Create a premium 10 second commercial for a choco brownie ice-cream cone — a chocolate wafer cone in a gold-and-brown wrapper, filled with chocolate ice cream, topped with brownie chunks and almond pieces under a glossy chocolate drizzle.\n\nUltra realistic product advertising, high end dessert commercial, macro cinematography, slow motion liquid simulation, studio lighting, 4K quality, photorealistic details.\n\nScene 1 (0 to 2s): Extreme macro of the empty chocolate wafer cone in its gold-and-brown wrapper, its embossed cocoa lattice texture catching light, tiny crumbs drifting off the ridges. Slow cinematic push-in across the surface. Hard key light rakes the wafer while a cool rim light traces the gold wrapper against electric cobalt-blue backdrop.\n\nScene 2 (2 to 5s): Thick chocolate ice cream swirls and coils into the same wafer cone in slow motion, glossy and dense, folding into a peak. Low angle orbit around the filling cone. Bright backlight creates glowing rim highlights on the creamy ribbons.\n\nScene 3 (5 to 7s): Brownie chunks and slivered almond pieces tumble down and land on the chocolate ice cream in slow motion, kicking up fine crumbs. Camera whip-pans then holds macro on impact. Backlit particles glitter against deep cobalt-blue.\n\nScene 4 (7 to 9s): Molten glossy chocolate drizzle pours over the toppings, coating brownie and almonds with a mirror sheen, edges thickening and beading. Slow motion macro tracking the flowing chocolate. Premium reflections, warm rim light.\n\nScene 5 (9 to 10s): The complete choco brownie ice-cream cone rises perfectly centered into frame, symmetrical composition, premium hero lighting, subtle camera hold on electric cobalt-blue.\n\nStyle: Luxury dessert advertising, realistic physics, rich cocoa textures, creamy chocolate, glossy drizzle, crisp wafer, gold-brown and electric cobalt-blue palette, hyper detailed product rendering, smooth speed-ramp transitions, elegant motion; no people, no hands, no text overlays, no watermark, no distortion, no extra products.\n\nAudio: Crisp wafer crackle, creamy swirl squelch, soft topping patter and thick chocolate pour synced to actions, over uplifting premium music resolving to clean silence.",
    "durationSec": 10,
    "aspectRatio": "9:16",
    "sheetUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-brownie-cone-v2.png",
    "videoUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-brownie-cone-v2.mp4"
  },
  {
    "id": "citrus-energy-can",
    "title": "Ice Rush Awakening",
    "product": "Ice-blue citrus energy drink can",
    "prompt": "Create a premium 15 second commercial for a slim 0.33L aluminium ice-blue citrus energy drink can with frosted matte finish and beads of condensation. Ultra realistic product advertising, high end energy drink commercial, macro cinematography, slow motion liquid simulation, studio lighting, 4K quality, photorealistic details.\n\nScene 1 (0 to 3s): Extreme macro on the slim ice-blue and silver frosted matte energy drink can standing on a white studio table, cold condensation beads swelling and trickling down the aluminium in slow motion. Camera slowly pushes in low across the table. Soft naturalistic key light with a cool rim highlight glazing the frosted metal.\n\nScene 2 (3 to 6s): Beside the can, a glossy sculpted cartoon punk head with a magenta-and-blue mohawk and chain piercings blinks awake, eyes snapping open. The ice-blue frosted can stays hero-lit and photoreal. Camera arcs in a slow orbit, hard key light catching the chrome piercings.\n\nScene 3 (6 to 9s): The punk head spots the ice-blue citrus energy drink can and its oversized jaw drops in exaggerated craving, drool glinting. Whip-pan snaps between craving face and the sweating can. Bright backlight creates glowing rim highlights on wet aluminium.\n\nScene 4 (9 to 12s): The head lunges and antics escalate, chains rattling, mohawk quivering, while condensation droplets scatter off the can in slow-motion crown splashes. Speed-ramped low-angle move keeps the frosted ice-blue can perfectly sharp and hero-lit.\n\nScene 5 (12 to 15s): Final packshot — the slim ice-blue and silver frosted matte energy drink can stands perfectly centered and upright in a halo of drifting cold mist, condensation beading. Symmetrical composition, premium hero lighting, subtle camera hold.\n\nStyle: Cinematic energy drink advertising, naturalistic pore-level realism, frosted aluminium and condensation textures, ice-blue silver and magenta accent palette, clean white studio environment, hyper detailed product rendering, smooth speed-ramp transitions, elegant motion, no text overlays, no watermark, no distortion, no extra products.\n\nAudio: Crisp condensation drips, a bright fizzy hiss, chain rattles and a cartoon jaw creak synced to the antics, over a punchy escalating electronic beat ending in a clean icy whoosh.",
    "durationSec": 15,
    "aspectRatio": "9:16",
    "sheetUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-citrus-energy-can-v2.png",
    "videoUrl": "https://eidasbvaktcndprdqgem.supabase.co/storage/v1/object/public/assets/library/sb-citrus-energy-can-v2.mp4"
  }
];
